

export const ATTRIBUTE_FILTERS = ["Cozy", "Romantic", "Family Friendly", "Good for groups", "Outdoor seating"];

export const INSPIRATIONS = [
  "Authentic Tacos al Pastor",
  "Spicy Ramen Challenge",
  "Cozy Italian Pasta",
  "Vegan Comfort Food",
  "Fresh Sushi Rolls",
  "Gourmet Burgers",
  "Bottomless Brunch Spots",
  "Late-night Korean BBQ",
  "Healthy Mediterranean Salads",
  "Artisanal Pizza",
  "Authentic Pho",
  "Family-style Dim Sum",
  "Farm-to-Table Experience",
  "Spicy Thai Green Curry",
  "Decadent Chocolate Desserts",
  "Craft Coffee Shops",
  "Hidden Gem Dive Bars",
  "Seafood Boil",
  "Southern BBQ Ribs",
  "Vegetarian Indian Buffet",
  "Dog-friendly Patios",
  "Restaurants with a View",
  "Interactive Hot Pot",
  "Açaí Bowls",
  "New York Style Bagels",
  "Bubble Tea Shops",
  "Wood-fired Steakhouse",
  "Gourmet Grilled Cheese",
  "Traditional English Breakfast",
  "Cheap and cheerful noodles",
  "Pancakes and Waffles",
  "Clam Chowder Bread Bowl",
  "Cuban Sandwiches",
  "Ice Cream Sundaes",
];
