-- =============================================================================
-- Migration: Add email_tokens table
-- Description: Stores verification and password reset tokens for custom email flow
-- Date: 2025-11-30
-- =============================================================================

-- Create the email_tokens table
-- This table stores tokens for email verification and password resets
-- Tokens are generated by the app and sent via our custom Resend emails
CREATE TABLE IF NOT EXISTS email_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The user this token belongs to
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- The unique token string (used in email links)
  token text UNIQUE NOT NULL,

  -- Type of token: 'confirmation' for signup, 'password_reset' for reset
  type text NOT NULL CHECK (type IN ('confirmation', 'password_reset')),

  -- When the token expires (24h for confirmation, 1h for password reset)
  expires_at timestamptz NOT NULL,

  -- When the token was created
  created_at timestamptz DEFAULT now(),

  -- Whether the token has been used (for tracking)
  used_at timestamptz DEFAULT NULL
);

-- Add comment for documentation
COMMENT ON TABLE email_tokens IS 'Stores email verification and password reset tokens for custom email flow';
COMMENT ON COLUMN email_tokens.type IS 'confirmation = signup verification, password_reset = password reset';
COMMENT ON COLUMN email_tokens.used_at IS 'Set when token is successfully used, prevents reuse';

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Fast token lookups (most common query)
CREATE INDEX IF NOT EXISTS idx_email_tokens_token ON email_tokens(token);

-- Find tokens by user (for cleanup or checking existing tokens)
CREATE INDEX IF NOT EXISTS idx_email_tokens_user_id ON email_tokens(user_id);

-- Find expired tokens (for cleanup jobs)
CREATE INDEX IF NOT EXISTS idx_email_tokens_expires_at ON email_tokens(expires_at);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS
ALTER TABLE email_tokens ENABLE ROW LEVEL SECURITY;

-- Users cannot directly access tokens (only via API routes with service role)
-- This is intentional - tokens should only be accessed server-side
CREATE POLICY "Service role only access" ON email_tokens
  FOR ALL
  USING (false)  -- No access for authenticated users
  WITH CHECK (false);

-- =============================================================================
-- CLEANUP FUNCTION (Optional - can be called periodically)
-- =============================================================================

-- Function to delete expired tokens
CREATE OR REPLACE FUNCTION cleanup_expired_email_tokens()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM email_tokens
  WHERE expires_at < now()
  RETURNING count(*) INTO deleted_count;

  RETURN COALESCE(deleted_count, 0);
END;
$$;

-- Comment for documentation
COMMENT ON FUNCTION cleanup_expired_email_tokens() IS 'Deletes expired email tokens. Can be called via cron job or manually.';

-- =============================================================================
-- EXAMPLE USAGE (for reference, not executed)
-- =============================================================================

/*
-- Insert a confirmation token (done in signup API route):
INSERT INTO email_tokens (user_id, token, type, expires_at)
VALUES (
  'user-uuid-here',
  'random-token-string',
  'confirmation',
  now() + interval '24 hours'
);

-- Insert a password reset token (done in reset-password API route):
INSERT INTO email_tokens (user_id, token, type, expires_at)
VALUES (
  'user-uuid-here',
  'random-token-string',
  'password_reset',
  now() + interval '1 hour'
);

-- Verify a token (done in confirm-email or verify-reset API route):
SELECT * FROM email_tokens
WHERE token = 'token-from-url'
  AND type = 'confirmation'
  AND expires_at > now()
  AND used_at IS NULL;

-- Mark token as used:
UPDATE email_tokens
SET used_at = now()
WHERE token = 'token-from-url';

-- Clean up expired tokens:
SELECT cleanup_expired_email_tokens();
*/
